### ISSUE TITLE
xan scrape

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/xan#508]
- [x] from html field or option to read file with --input-dir
- [ ] tables
- [x] --sep
- [x] --evaluate-file
- [x] parallelized
- [ ] single file option?
- [x] --iter --root --field or imagine something along the lines of select -e or agg
- [x] title
- [x] optimized title with regex
- [x] urls
- [x] contains with regex
- [ ] document and note sass
- [ ] canonical
- [ ] images
- [ ] links
- [x] test entities
- [x] ld json schema org type
- [x] test case with urljoin on file column

Functions:

- [x] contains
- [x] parent
- [ ] find_parent
- [ ] next_sibling, prev_sibling

Extractors:

- [x] inner_html
- [x] outer_html
- [x] ldjson

https://github.com/medialab/ural/blob/master/ural/links_from_html.py

**Comment by Yomguithereal** [comment]
Example:

https://www.mediapart.fr/journal/fil-dactualites/071224/paris-un-serrurier-meurt-poignarde-un-client-en-garde-vue

```bash
xan scrape html report.csv -e 'scrape("h1.page-title") as title'
```

**Comment by Yomguithereal** [comment]
Attempting to convert this one:

```yml
---
iterator: article
fields:
    title:
        sel: h2 > a
    url:
        sel: h2 > a
        attr: href
    author:
        sel: username > a
    up:
        sel: .upvotes
    down:
        sel: .downvotes
```

```bash
xan scrape --select article ... '"h2 > a" as title, "h2 > a" extract "href" with lower(_)'
```
